[build]
  publish = "."
  functions = "netlify/functions"
  command = "# no build command needed"

[[redirects]]
  from = "/astro"
  to = "/astro.html"
  status = 200

[[redirects]]
  from = "/novaai"
  to = "/novaai.html"
  status = 200

[[redirects]]
  from = "/id"
  to = "/id.html"
  status = 200

[[redirects]]
  from = "/get-started"
  to = "/get-started.html"
  status = 200

[[redirects]]
  from = "/status"
  to = "/status.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/.netlify/functions/rss"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"

[functions]
  node_bundler = "esbuild"

[functions.scheduled-rss]
  schedule = "0 */6 * * *"

[[redirects]]
  from = "/blog/feed.xml"
  to = "/.netlify/functions/scheduled-rss"
  status = 200
  force = true

[[headers]]
  for = "/blog/feed.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=21600"
    Access-Control-Allow-Origin = "*"
