[build]
  publish = "."

[[redirects]]
  from = "/astro"
  to = "/astro.html"
  status = 200

[[redirects]]
  from = "/novaai"
  to = "/novaai.html"
  status = 200

[[redirects]]
  from = "/id"
  to = "/id.html"
  status = 200

[[redirects]]
  from = "/get-started"
  to = "/get-started.html"
  status = 200

[[redirects]]
  from = "/status"
  to = "/status.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
